name       : lilv
version    : 0.24.4
release    : 4
source     :
    - https://github.com/drobilla/lilv/archive/v0.24.4.tar.gz : 7c6e3f630367213118446a89f0f629c8af13773ca109895d6057b64900ff8423
license    : ISC
component  : programming.library
summary    : A library to make the use of LV2 plugins as simple as possible
description: |
    Lilv is the successor to SLV2, rewritten to be significantly faster and have minimal dependencies. It is stable, well-tested software (the included test suite covers over 90% of the code) in use by several applications.
builddeps  :
    - pkgconfig(lv2)
    - pkgconfig(serd-0)
    - pkgconfig(sord-0)
    - pkgconfig(sratom-0)
setup      : |
    %waf_configure --configdir=/etc --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
    completionsDir=$installdir/usr/share/bash-completion/completions/
    install -dm644 $completionsDir
    mv $installdir/etc/bash_completion.d/lilv $completionsDir
    rm -rf $installdir/etc
