name        : lilv
version     : 0.22.0
release     : 1
source      :
    - http://download.drobilla.net/lilv-0.22.0.tar.bz2 : cd279321223ef11ca01551767d3c16d68cb31f689e02320a0b2e37b4f7d17ab4
license     : ISC
component   : programming
summary     : A library to make the use of LV2 plugins as simple as possible
description : |
    Lilv is the successor to SLV2, rewritten to be significantly faster and have minimal dependencies. It is stable, well-tested software (the included test suite covers over 90% of the code) in use by several applications.
builddeps   :
    - pkgconfig(lv2)
    - pkgconfig(serd-0)
    - pkgconfig(sord-0)
    - pkgconfig(sratom-0)
setup       : |
    ./waf configure --prefix=%PREFIX% --libdir=%libdir% --configdir=/etc
build       : |
    ./waf build
install     : |
    completionsDir=$installdir/usr/share/bash-completion/completions/
    ./waf install --destdir="$installdir"
    install -dm644 $completionsDir
    mv $installdir/etc/bash_completion.d/lilv $completionsDir
    rm -rf $installdir/etc
