name        : lilv
version     : 0.22.0
release     : 1
source      :
    - http://download.drobilla.net/lilv-0.22.0.tar.bz2 : cd279321223ef11ca01551767d3c16d68cb31f689e02320a0b2e37b4f7d17ab4
license     :
    - ISC
component   : programming.devel
summary     : A library to make the use of LV2 plugins as simple as possible
builddeps   :
    - lv2-devel
    - serd-devel
    - sord-devel
    - sratom-devel
description : |
    Lilv is the successor to SLV2, rewritten to be significantly faster and have minimal dependencies. It is stable, well-tested software (the included test suite covers over 90% of the code) in use by several applications.
setup       : |
    %workdir%/waf configure --prefix=%PREFIX% --libdir=%libdir%
build       : |
    %workdir%/waf build
install     : |
    %workdir%/waf install --destdir="$installdir"
