name       : lilv
version    : 0.24.2
release    : 3
source     :
    - http://download.drobilla.net/lilv-0.24.2.tar.bz2 : f7ec65b1c1f1734ded3a6c051bbaf50f996a0b8b77e814a33a34e42bce50a522
license    : ISC
component  : programming.library
summary    : A library to make the use of LV2 plugins as simple as possible
description: |
    Lilv is the successor to SLV2, rewritten to be significantly faster and have minimal dependencies. It is stable, well-tested software (the included test suite covers over 90% of the code) in use by several applications.
builddeps  :
    - pkgconfig(lv2)
    - pkgconfig(serd-0)
    - pkgconfig(sord-0)
    - pkgconfig(sratom-0)
setup      : |
    %waf_configure --configdir=/etc --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
    completionsDir=$installdir/usr/share/bash-completion/completions/
    install -dm644 $completionsDir
    mv $installdir/etc/bash_completion.d/lilv $completionsDir
    rm -rf $installdir/etc
